git:
  submodules: false

sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="brew update && brew unlink python && brew install protobuf && brew install snappy && brew install lz4"
        - UUID=`date +%d-%m-%y-%H-%M-%S`
language: node_js

node_js:
  - node

before_install:
  - eval "${MATRIX_EVAL}"
  - git submodule update --init --recursive
  - cd bluzelle-js
  - yarn install
  - webpack
  - cd ..
  - yarn install

before_script:
  - |
    if [ "$TRAVIS_BRANCH" = "master" ]; then
        export ADDRESS=testnet.bluzelle.com;
      else
        export ADDRESS=testnet-dev.bluzelle.com;
    fi

script:
  - yarn smoke-test
  - yarn performance-testing
