git:
  submodules: false

sudo: required

matrix:
  include:
    - os: osx

language: node_js

node_js:
  - "node" # Use latest NodeJS

jobs:
  include:
    - script: ./soak-test.sh

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init
  - cd bluzelle-js
  - npm install
  - cd ..
  - npm install

dependencies:
  - bluzelle-js: git+ssh://git@github.com:bluzelle/bluzelle-js.git
