git:
  submodules: false

sudo: required

matrix:
  include:
    - os: osx

language: node_js

node_js:
  - node

before_install:
  - git submodule update --init --recursive
  - cd bluzelle-js
  - yarn install
  - webpack
  - cd ..
  - yarn install

script: ./soak-test.sh
